version: '3.8'

services:

  postgres-author:
    image: postgres:15
    environment:
      POSTGRES_DB: bank-rest-main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
