spring:
  application:
    name: bank-rest-main

  datasource:
    url: jdbc:postgresql://localhost:6543/bank-rest-main
    username: postgres
    password: postgre
    driver-class-name:  org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    change-log: classpath:/db/migration/db.changelog-master.yaml

server:
  port: 8080
  servlet:
    context-path: /bank-rest

logging:
  level:
    org:
      springframework:
        root: INFO
        springfox: INFO
        security: DEBUG



app:
  crypto:
    secret-key: u7dB3iYKDyNKNDY7HK0Rq4Yu9fo6FD0xDVjDmSeVj2c=
    access-secret: access-secret-key-very-long-1234567890
    refresh-secret: refresh-secret-key-very-long-1234567890