spring:
  application:
    name: bank-rest-main

  datasource:
    url: jdbc:postgresql://localhost:6543/bank-rest-main
    username: postgres
    password: postgre
    driver-class-name:  org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    root: INFO
    springfox: INFO
